#!/usr/bin/env python3
"""
Rod's Golf Model — DataGolf ingestion pipeline (Path A: wrap DataGolf)
=====================================================================

Run this on YOUR machine (it needs internet + your DataGolf key).
It pulls the DataGolf feeds, maps them into the shapes Rod's Model expects,
and writes `rods_data.json` next to the HTML page. The page reads that file.

SECURITY: never hard-code your key here or paste it into a chat. Set it as an
env var:   export DG_KEY="your_key_here"

Usage:
    export DG_KEY="..."
    python rods_pipeline.py                 # PGA/euro default -> writes rods_data.json
    python rods_pipeline.py --tour euro      # if The Open is under the euro feed
    python rods_pipeline.py --watch 300      # re-pull every 5 min during the round

Path B migration: everything DataGolf-specific lives in the fetch_* functions and
the MAP_* mapping dicts. To compute your own Birkdale weights later, replace
build_projections()'s use of the decomposition 'fit' field with your own engine's
output — the JSON shape the page consumes does not change.

MODEL vs MARKET (updated this session): matchup "model%" is now generated by
sim_engine.py from projected scores + this event's course-fit variance/blowup —
NOT passed through from DataGolf's own matchup probability. Comparing DataGolf's
model to a DataGolf-derived market number was comparing DG to itself; it couldn't
show real edge no matter what the numbers said. "market%" still comes straight off
DataGolf's book-sourced odds, which is the only side of that comparison that
should come from them.

course_fit_table.json (written by load_course_fit_xlsx.py from
course_fit_template.xlsx) is now read automatically if present, and used both
for the F table and as the course-level scoreSD/blowup input to the sim. Falls
back to the hardcoded Birkdale/Bay Hill rows if that file doesn't exist yet.
"""

import os
import sys
import json
import time
import argparse
import urllib.request
import urllib.parse
import urllib.error
from collections import defaultdict

from sim_engine import run_matchup_sim, run_finish_sim, TOUR_BASELINE_SD, DEFAULT_BLOWUP

BASE = "https://feeds.datagolf.com"
OUT  = "rods_data.json"
COURSE_FIT_TABLE = "course_fit_table.json"   # written by load_course_fit_xlsx.py, optional

# ---- endpoints we use for Path A ----
EP = {
    "decomp":   "/preds/player-decompositions",   # fit-adjustment breakdown + final_pred (confirmed live: age/country/
                                                     # course-history/fit adjustments feeding a final_pred number —
                                                     # NOT raw sg_ott/sg_app/etc, despite what the field name suggests)
    "skill":    "/preds/skill-ratings",            # THE actual source of sg_ott/sg_app/sg_arg/sg_putt/sg_t2g
                                                     # (confirmed via DataGolf's own API docs — separate endpoint
                                                     # from decompositions, season-level skill ratings by category)
    "pretourn": "/preds/pre-tournament",          # win/top-N/make-cut probabilities (confirmed live: NO projected
                                                     # score field exists here despite the original assumption)
    "matchups": "/betting-tools/matchups",        # model vs book 2-ball odds
    "outrights":"/betting-tools/outrights",       # tournament win/top-N market odds (per DataGolf's own docs)
    "field":    "/field-updates",                  # tee times / wave (AM-PM)
}


def get_key():
    key = os.environ.get("DG_KEY")
    if not key:
        sys.exit("ERROR: set your key first ->  export DG_KEY=\"your_datagolf_key\"")
    return key


def fetch(endpoint, key, **params):
    """GET a DataGolf feed as JSON. Returns parsed python or raises."""
    params.setdefault("file_format", "json")
    params["key"] = key
    url = f"{BASE}{endpoint}?{urllib.parse.urlencode(params)}"
    try:
        with urllib.request.urlopen(url, timeout=30) as r:
            raw = r.read().decode("utf-8")
    except urllib.error.HTTPError as e:
        # surface DataGolf's own error message (bad key, wrong tour, no event, etc.)
        body = e.read().decode("utf-8", "ignore")
        raise SystemExit(f"HTTP {e.code} on {endpoint}: {body[:300]}")
    except urllib.error.URLError as e:
        raise SystemExit(f"Network error on {endpoint}: {e.reason}")
    try:
        return json.loads(raw)
    except json.JSONDecodeError:
        raise SystemExit(f"Non-JSON reply on {endpoint} (first 200 chars): {raw[:200]}")


def as_rows(payload):
    """DataGolf wraps rows in different keys depending on endpoint; normalize to a list."""
    if isinstance(payload, list):
        return payload
    # 'odds' is here specifically for outrights: confirmed live that its top-level payload
    # has BOTH 'books_offering' (a flat list of book name strings) and 'odds' (the real
    # 156-player list) — the generic fallback below picked books_offering first since it's
    # also a list and came first in the dict, silently truncating "the field" to 13 book names.
    for k in ("players", "matchups", "match_list", "odds", "field", "data", "baseline", "rows"):
        if isinstance(payload, dict) and isinstance(payload.get(k), list):
            return payload[k]
    # some feeds nest under a single dict key -> take first list value found
    if isinstance(payload, dict):
        for v in payload.values():
            if isinstance(v, list):
                return v
    return []


def num(x, nd=1):
    """Round to nd decimals, pass through None for missing (renders as 'nan')."""
    if x is None or x == "":
        return None
    try:
        return round(float(x), nd)
    except (TypeError, ValueError):
        return None


# ------------------------------------------------------------------
# MAP 1: projections table (the `P` array)
# ------------------------------------------------------------------
# Approximate baseline round score used to convert final_pred (a strokes-
# gained-vs-field prediction, confirmed live to run ~2.0-2.7 for the top of
# the field) into an absolute score for the PROJ column. This is a rough
# constant, not derived from real course data — Path B (computing your own
# Birkdale scoring baseline from round-level history, see course_fit_engine.py)
# replaces this with something real. Until then it's directionally correct
# (better predicted players get a lower/better PROJ number) but the absolute
# number is an approximation. 71.0 ≈ Birkdale's par 70 + a small toughening
# margin typical of Open Championship setups.
BASELINE_ROUND_SCORE = 71.0


def build_skill_ratings(skill_payload):
    """
    Map DataGolf skill-ratings -> {dg_id: {ttg, ott, app, put, arg}, name: {...}}
    This is the actual source of category strokes-gained (confirmed via DataGolf's
    docs: sg_putt, sg_arg, sg_app, sg_ott, sg_t2g, sg_bs, sg_total, ...).
    Indexed by BOTH dg_id and normalized name since join reliability across
    DataGolf's different feeds is inconsistent — dg_id is preferred when present.
    """
    def pick(row, *names):
        for n in names:
            if n in row and row[n] is not None:
                return row[n]
        return None

    by_id, by_name = {}, {}
    for r in as_rows(skill_payload):
        vals = {
            "ttg": num(pick(r, "sg_t2g", "t2g")),
            "ott": num(pick(r, "sg_ott", "ott")),
            "app": num(pick(r, "sg_app", "app")),
            "put": num(pick(r, "sg_putt", "sg_put", "putt")),
            "arg": num(pick(r, "sg_arg", "arg")),
        }
        dg_id = pick(r, "dg_id")
        name = pick(r, "player_name", "name")
        if dg_id is not None:
            by_id[dg_id] = vals
        if name:
            by_name[normalize_name(name)] = vals
    return by_id, by_name


def build_projections(decomp_payload, skill_by_id, skill_by_name):
    """
    Map DataGolf player-decompositions + skill-ratings -> Rod's `P` rows:
      [name, proj, ttg, ott, app, put, arg, fit]

    - name/dg_id/proj/fit come from player-decompositions (confirmed live fields:
      player_name, dg_id, final_pred, total_fit_adjustment)
    - ttg/ott/app/put/arg come from skill-ratings, joined by dg_id (falls back
      to normalized name if dg_id isn't present in either feed)
    """
    def pick(row, *names):
        for n in names:
            if n in row and row[n] is not None:
                return row[n]
        return None

    rows = as_rows(decomp_payload)
    out = []
    for r in rows:
        name = pick(r, "player_name", "name")
        if not name:
            continue
        norm_name = normalize_name(name)
        dg_id = pick(r, "dg_id")
        skill = skill_by_id.get(dg_id) if dg_id is not None else None
        if skill is None:
            skill = skill_by_name.get(norm_name, {})

        final_pred = pick(r, "final_pred", "baseline_pred")
        proj = num(BASELINE_ROUND_SCORE - final_pred) if final_pred is not None else None

        out.append({
            "name": norm_name,
            "proj": proj,
            "ttg":  skill.get("ttg"),
            "ott":  skill.get("ott"),
            "app":  skill.get("app"),
            "put":  skill.get("put"),
            "arg":  skill.get("arg"),
            "fit":  num(pick(r, "total_fit_adjustment", "course_fit", "fit", "fit_adj", "cf")),
            "_dg_id": dg_id,
        })
    # sort best (lowest) proj first; None sinks to bottom
    out.sort(key=lambda x: (x["proj"] is None, x["proj"] if x["proj"] is not None else 999))
    return out


# ------------------------------------------------------------------
# MAP 2: matchups table (the `M` array)
# ------------------------------------------------------------------
# Book preference order when picking which sportsbook's price to show as
# "market" — real books first (most consistently present across matchups per
# the live sample), datagolf's own line last since that's their model output,
# not a market price, and we want market% to be genuinely market-sourced.
BOOK_PREFERENCE = ("draftkings", "bet365", "bovada", "betcris", "fanduel", "pinnacle", "datagolf")
# draftkings is first because that's the book Rod actually has an account with — the price
# shown on the page should be the price he can actually get, not just the first one found.
# Falls back down the list only when DraftKings hasn't posted a price for that player/market.


def pick_book_price(odds_dict):
    """
    DataGolf's real shape (confirmed on a live pull): odds is nested per book,
    e.g. {"bet365": {"p1": "-111", "p2": "-111"}, "bovada": {...}, ...} — not
    a flat p1_odds field. Walk BOOK_PREFERENCE and return BOTH players' prices
    from the first book that has them, plus which book it came from. Both
    sides are needed (not just p1) so a FADE call — which means betting the
    *other* player — can still show the correct real price rather than
    reusing p1's price for a bet that's actually on p2.

    Also returns book_count — how many books actually posted a price for this
    matchup at all, not just which one we ended up using. A price backed by
    one thin book deserves less confidence than one where 7 books agree, even
    if the number itself looks the same on the page.
    """
    if not isinstance(odds_dict, dict):
        return None, None, None, 0
    book_count = sum(1 for entry in odds_dict.values()
                      if isinstance(entry, dict) and entry.get("p1") is not None)
    for book in BOOK_PREFERENCE:
        entry = odds_dict.get(book)
        if isinstance(entry, dict) and entry.get("p1") is not None:
            return entry["p1"], entry.get("p2"), book, book_count
    # fall back to whatever book is present, in whatever order the dict gives us
    for book, entry in odds_dict.items():
        if isinstance(entry, dict) and entry.get("p1") is not None:
            return entry["p1"], entry.get("p2"), book, book_count
    return None, None, None, book_count


def pick_single_book_price(row):
    """
    Same book-preference walk as pick_book_price, but for outrights markets
    where each book's price sits directly on the row as a flat field — e.g.
    {"bet365": "+500", "draftkings": "+450", ..., "player_name": "...", "dg_id": ...}
    — confirmed live: NOT nested under a sub-'odds' key the way matchups is.
    "datagolf" is excluded even though it's in BOOK_PREFERENCE's fallback
    position — confirmed live it's a nested {"baseline":, "baseline_history_fit":}
    object, not a plain price, and would silently return a dict as a "price"
    if not filtered out here.
    """
    if not isinstance(row, dict):
        return None, None
    for book in BOOK_PREFERENCE:
        if book == "datagolf":
            continue  # not a real market price — see docstring
        entry = row.get(book)
        if isinstance(entry, (str, int, float)):
            return entry, book
    # fall back to any other book-shaped field present, skipping known non-price keys
    skip_keys = {"player_name", "name", "dg_id", "datagolf"}
    for k, entry in row.items():
        if k in skip_keys:
            continue
        if isinstance(entry, (str, int, float)):
            return entry, k
    return None, None


def build_matchups(matchup_payload, wave_by_name, proj_by_name, course_row, n_rounds=1):
    """
    Map DataGolf matchup tool -> Rod's `M` rows:
      [playerA, playerB, wave, modelPct, marketPct, priceA, priceB]

    Pulls the two players and the book price/market number from DataGolf, but
    the model% comes from sim_engine.py (projected scores + this event's
    course variance/blowup), NOT from DataGolf's own matchup probability —
    see the module docstring for why that swap matters.

    priceB (player B's own price) is captured alongside priceA so a FADE call
    — which means betting player B, not A — can show a real, correct price
    instead of reusing A's price for a bet that's actually on B.
    """
    def pick(row, *names):
        for n in names:
            if n in row and row[n] is not None:
                return row[n]
        return None

    raw_rows = as_rows(matchup_payload)

    # DataGolf posts the SAME pairing as two separate entries when a book offers both a
    # standard 2-way market (ties refunded — "ties": "void") and a 3-way market (ties as
    # their own outcome — "ties": "separate bet offered"). Confirmed live: the 3-way variant
    # carries far fewer books and never includes DraftKings, so keeping both just duplicates
    # every such pairing on the page with a worse, less-actionable price.
    #
    # SEPARATE, BIGGER ISSUE (confirmed against Rod's real DraftKings tee-group list): the feed
    # also contains "alternate 2-ball" pairings between players who are NOT in the same tee
    # group at all — e.g. "McIlroy vs Schauffele" when their real groups are McIlroy/Bridgeman
    # and Fox/Schauffele. These alternates only ever appear ONCE, as "ties":"void", with no
    # "ties":"separate bet offered" sibling for that exact pair. Every genuine tee-group pairing
    # in Rod's real list appeared TWICE — both tie structures — except one (missing its void
    # entry entirely on DataGolf's end). So: a pair is a real tee-group matchup if a "separate
    # bet offered" entry exists for it (use the void entry for the actual price if one exists,
    # since that's the bettable 2-way market; fall back to the separate-bet entry's price only
    # if no void version showed up). Pairs with ONLY a void entry and no separate-bet sibling
    # are alternates and get dropped from this table entirely.
    by_pair = defaultdict(list)
    for r in raw_rows:
        p1_raw = pick(r, "p1_player_name", "player1", "p1")
        p2_raw = pick(r, "p2_player_name", "player2", "p2")
        if not p1_raw or not p2_raw:
            continue
        by_pair[(p1_raw, p2_raw)].append(r)

    rows = []
    for key, entries in by_pair.items():
        tie_types = {e.get("ties") for e in entries}
        if "separate bet offered" not in tie_types:
            continue  # alternate/cross-group pairing, not a real tee-group matchup — drop it
        void_entry = next((e for e in entries if e.get("ties") == "void"), None)
        rows.append(void_entry if void_entry is not None else entries[0])

    pairs = []
    meta = []
    for r in rows:
        p1 = pick(r, "p1_player_name", "player1", "p1")
        p2 = pick(r, "p2_player_name", "player2", "p2")
        if not p1 or not p2:
            continue
        p1 = normalize_name(p1); p2 = normalize_name(p2)
        # book implied — DataGolf nests odds per sportsbook; walk BOOK_PREFERENCE
        market = pick(r, "p1_implied_prob", "market_prob", "p1_book_prob")
        priceA, priceB, book_used, book_count = pick_book_price(r.get("odds"))
        market_prob = as_prob(market)
        if market_prob is None and priceA is not None:
            market_prob = implied_prob_from_american(priceA)  # derive from the price if DG didn't give a % directly
        w1 = wave_by_name.get(p1, "?"); w2 = wave_by_name.get(p2, "?")
        wave = w1 if w1 == w2 else f"{w1}/{w2}"
        pairs.append((p1, p2))
        priceA_display = f"{priceA} ({book_used})" if priceA is not None else "—"
        priceB_display = f"{priceB} ({book_used})" if priceB is not None else "—"
        # real no-vig: normalize both sides' implied probabilities so they sum to exactly
        # 1.0, removing the book's overround. Previously this column was a placeholder that
        # just copied market% unchanged — confirmed on the live page (every row showed
        # No-Vig% == Market%, which should never happen once real vig is actually removed).
        no_vig = None
        if priceA is not None and priceB is not None:
            impliedA = implied_prob_from_american(priceA)
            impliedB = implied_prob_from_american(priceB)
            if impliedA is not None and impliedB is not None and (impliedA + impliedB) > 0:
                no_vig = impliedA / (impliedA + impliedB)
        # skill-gap flag: large PROJ differences are exactly where the flat, shared variance
        # assumption (same sd for every player) breaks down hardest, and real books tend to
        # price "obvious" mismatches efficiently — so a big edge on a big skill gap is more
        # often model error than real value, not less. Flag it rather than hide it; the person
        # placing the bet should see the reason to double-check, not have it auto-filtered.
        meanA = proj_by_name.get(p1, {}).get("mean")
        meanB = proj_by_name.get(p2, {}).get("mean")
        skill_gap = abs(meanA - meanB) if (meanA is not None and meanB is not None) else None
        meta.append({"a": p1, "b": p2, "wave": wave, "market": market_prob,
                      "price": priceA_display, "priceB": priceB_display, "noVig": no_vig,
                      "skillGap": round(skill_gap, 2) if skill_gap is not None else None,
                      "bookCount": book_count})

    # one batched sim call for every matchup on the slate
    model_probs = run_matchup_sim(proj_by_name, pairs, course_row=course_row, n_rounds=n_rounds)

    out = []
    for (p1, p2), m in zip(pairs, meta):
        m["model"] = model_probs.get((p1, p2))  # None if either player had no projection to sim from
        out.append(m)

    # sort by edge desc; unsimmed/unmarketed rows sink to the bottom
    def edge(m):
        if m["model"] is None or m["market"] is None:
            return -999
        return m["model"] - m["market"]
    out.sort(key=edge, reverse=True)
    return out


# ------------------------------------------------------------------
# MAP 4: outright win market (the `W` array) — tournament winner odds
# ------------------------------------------------------------------
def build_outrights_market(outrights_payload):
    """
    Map DataGolf's outrights market -> {normalized_name: {"market": prob, "price": display_str}}
    Single-outcome market (unlike matchups' p1/p2 pairs), so each book maps
    to one price per player — see pick_single_book_price.
    """
    def pick(row, *names):
        for n in names:
            if n in row and row[n] is not None:
                return row[n]
        return None

    out = {}
    for r in as_rows(outrights_payload):
        name = pick(r, "player_name", "name")
        if not name:
            continue
        norm_name = normalize_name(name)
        price, book_used = pick_single_book_price(r)  # prices sit directly on the row, confirmed live
        market_prob = implied_prob_from_american(price) if price is not None else None
        out[norm_name] = {
            "market": market_prob,
            "price": f"{price} ({book_used})" if price is not None else "—",
        }
    return out


def build_outrights(finish_sim_results, outrights_market, sim_key):
    """
    Merge the full-field finish simulation (sim_engine.run_finish_sim) with
    DataGolf's real market odds for one market -> rows:
      [name, modelPct, marketPct, price]
    sim_key selects which of the sim's outputs to use: 'win', 'top5', 'top10', 'top20'.
    Included for every player the sim has a result for, even if no market
    price was found (renders as "—" on the page, same convention as the
    other tables).
    """
    out = []
    for name, sim_row in finish_sim_results.items():
        mkt = outrights_market.get(name, {})
        out.append([name, round(sim_row[sim_key], 4), mkt.get("market"), mkt.get("price", "—")])
    out.sort(key=lambda r: -r[1])  # best model% first
    return out


def as_prob(x):
    """Coerce a probability that might be 0-1 or 0-100 into a 0-1 float."""
    if x is None or x == "":
        return None
    try:
        v = float(x)
    except (TypeError, ValueError):
        return None
    return v / 100.0 if v > 1.0 else v


def implied_prob_from_american(price):
    """American odds -> implied probability (still vig-inclusive; this is 'market', not 'no-vig')."""
    try:
        p = float(price)
    except (TypeError, ValueError):
        return None
    if p > 0:
        return 100.0 / (p + 100.0)
    elif p < 0:
        return -p / (-p + 100.0)
    return None


# ------------------------------------------------------------------
# MAP 3: wave / draw from field updates
# ------------------------------------------------------------------
def build_waves(field_payload):
    """
    Map field-updates -> {player_name: 'AM'|'PM'} using round-1 tee time,
    and compute a draw-bias placeholder (real bias needs forecast + results).
    """
    def pick(row, *names):
        for n in names:
            if n in row and row[n] is not None:
                return row[n]
        return None
    waves = {}
    for r in as_rows(field_payload):
        nm = normalize_name(pick(r, "player_name", "name") or "")
        tt = pick(r, "r1_teetime", "teetime", "tee_time")
        if not nm or not tt:
            continue
        waves[nm] = classify_wave(tt)
    return waves


def classify_wave(teetime):
    """Very rough AM/PM split from a tee-time string like '2026-07-16T13:20' or '1:20 PM'."""
    s = str(teetime).lower()
    if "pm" in s:
        # 12-something pm is borderline; treat >=12:00 as PM
        return "PM"
    if "am" in s:
        return "AM"
    # ISO-ish: grab the hour
    for sep in ("t", " "):
        if sep in s:
            tail = s.split(sep)[-1]
            hh = tail[:2]
            if hh.isdigit():
                return "AM" if int(hh) < 12 else "PM"
    return "?"


# ------------------------------------------------------------------
# name normalization so the three feeds join cleanly
# ------------------------------------------------------------------
def normalize_name(name):
    """DataGolf often returns 'Last, First'; the page shows 'First Last'. Normalize to 'First Last'."""
    name = name.strip()
    if "," in name:
        last, first = [p.strip() for p in name.split(",", 1)]
        return f"{first} {last}"
    return name


# ------------------------------------------------------------------
# course-fit table (the `F` array). Prefers course_fit_table.json, written by
# load_course_fit_xlsx.py from your filled-in course_fit_template.xlsx. Falls
# back to the hardcoded Birkdale/Bay Hill reference rows if that file isn't
# there yet (i.e. you haven't filled in the spreadsheet, or run the loader).
# ------------------------------------------------------------------
def course_fit_placeholder():
    return [
        # [course, renewals, scoreAdj, scoreSD, blowup, wOTT,wAPP,wARG,wPUT, distPrem, recovPen, cutParar, grass]
        ["Royal Birkdale (2026)", 10, 2.4, 3.8, 0.13, 1.10, 1.15, 1.30, 1.00, -0.10, 0.30, 4.0, "fescue/bent"],
        ["Bay Hill (ref: parkland)", 15, 1.8, 3.1, 0.08, 1.15, 1.20, 1.05, 0.85, 0.30, 0.22, 2.0, "bermuda"],
    ]


def load_course_fit(target_course_name):
    """
    Returns (F, target_row) where F is the page-ready course-fit table and
    target_row is a {'scoreSD':, 'blowup':} dict for whichever row matches
    target_course_name (the REAL current event's course, from DataGolf's own
    event payload — see build()) — used to seed the sim's course-level variance.

    Falls back to TOUR-WIDE baseline defaults (not to whatever row happens to
    be first in the table) when no course-specific data exists for the current
    event. This matters: the hardcoded reference rows below are Royal Birkdale
    (an extreme, high-variance links course) and Bay Hill — silently defaulting
    a brand-new tournament at a different course to Birkdale's atypical numbers
    would distort every model probability, not just look slightly off.
    """
    def neutral_fallback():
        return {"scoreSD": TOUR_BASELINE_SD, "blowup": DEFAULT_BLOWUP}

    if os.path.exists(COURSE_FIT_TABLE):
        with open(COURSE_FIT_TABLE) as f:
            data = json.load(f)
        F = data.get("F") or []
        if F:
            target = next((row for row in F if target_course_name.lower() in str(row[0]).lower()), None)
            if target:
                return F, {"scoreSD": target[3], "blowup": target[4]}
            return F, neutral_fallback()
    F = course_fit_placeholder()
    target = next((row for row in F if target_course_name.lower() in str(row[0]).lower()), None)
    if target:
        return F, {"scoreSD": target[3], "blowup": target[4]}
    return F, neutral_fallback()


def fetch_matchups_with_fallback(key, tour):
    """
    Try tournament_matchups first (72-hole market); if DataGolf reports it's
    not being offered yet (confirmed on a live pull: match_list comes back as
    a string like "No tournament_matchups being offered right now." instead
    of a list), fall back to round_matchups, which was live and populated.
    Returns (rows, market_used, rounds_for_sim).
    """
    try:
        payload = fetch(EP["matchups"], key, tour=tour, market="tournament_matchups", odds_format="american")
        rows = as_rows(payload)
        if rows:
            return rows, "tournament_matchups", 4
        print("   tournament_matchups not posted yet — falling back to round_matchups")
    except SystemExit as e:
        print(f"   tournament_matchups failed ({e}) — falling back to round_matchups")

    try:
        payload = fetch(EP["matchups"], key, tour=tour, market="round_matchups", odds_format="american")
        rows = as_rows(payload)
        return rows, "round_matchups", 1
    except SystemExit as e:
        print(f"   round_matchups also failed ({e}) — leaving matchups empty")
        return [], None, 1


def build(tour, matchup_rounds=None, finish_trials=10000):
    key = get_key()
    print(f"[1/6] player decompositions ({tour}) ...")
    decomp = fetch(EP["decomp"], key, tour=tour)
    print(f"[2/6] skill ratings ...")
    skill = fetch(EP["skill"], key)  # not tour-specific — season-level skill ratings
    print(f"[3/6] pre-tournament predictions ({tour}) ...")
    pretourn = fetch(EP["pretourn"], key, tour=tour, odds_format="percent")  # win/top-N/make-cut probs;
    # not used directly — no projected-score field exists here (confirmed live). Kept in
    # case you want to sanity-check the finish sim against DataGolf's own probabilities.
    print(f"[4/6] field / tee times ({tour}) ...")
    field = fetch(EP["field"], key, tour=tour)
    print(f"[5/6] matchups ({tour}) ...")
    matchup_rows, market_used, auto_rounds = fetch_matchups_with_fallback(key, tour)
    print(f"   using market: {market_used} ({len(matchup_rows)} matchups)")
    print(f"[6/6] outrights (win/top5/top10/top20, {tour}) ...")
    # market param values per DataGolf's docs: win, top_5, top_10, top_20 (also make_cut/frl exist,
    # not pulled here — not asked for, and make_cut needs real cut-line modeling this sim doesn't do yet)
    FINISH_MARKETS = [("win", "win"), ("top_5", "top5"), ("top_10", "top10"), ("top_20", "top20")]
    outrights_markets = {}
    for dg_market, sim_key in FINISH_MARKETS:
        try:
            payload = fetch(EP["outrights"], key, tour=tour, market=dg_market, odds_format="american")
            outrights_markets[sim_key] = build_outrights_market(payload)
            print(f"   {dg_market}: {len(outrights_markets[sim_key])} players with a market price")
        except SystemExit as e:
            print(f"   {dg_market} unavailable ({e}) — that market will be model-only")
            outrights_markets[sim_key] = {}

    # explicit --matchup-rounds always wins if the caller passed one; otherwise
    # use whatever round count matches the market that actually had data
    n_rounds = matchup_rounds if matchup_rounds is not None else auto_rounds

    skill_by_id, skill_by_name = build_skill_ratings(skill)
    proj = build_projections(decomp, skill_by_id, skill_by_name)
    waves = build_waves(field)

    # Confirmed live (decompositions payload top-level keys): DataGolf's own response already
    # carries the real event_name and course_name — no reason to hardcode a specific
    # tournament's name here, which would silently mislabel every future event (and, worse,
    # mistag Tracker bets under the wrong tournament and feed the wrong course's variance
    # into the sim). Falls back to generic labels only if DataGolf's payload is missing them.
    event_name = decomp.get("event_name") or "Unknown Event"
    course_name = decomp.get("course_name") or event_name

    F, target_course_row = load_course_fit(course_name)
    proj_by_name = {r["name"]: {"mean": r["proj"], "sd": None} for r in proj}
    # NOTE: n_rounds sums that many simulated rounds per player in the sim, matched
    # automatically to whichever market actually had data (4 for tournament_matchups,
    # 1 for round_matchups). This ignores cuts/WDs on the 4-round path — a real 72-hole
    # matchup settles on made-cut rounds only, which this sim doesn't model yet.
    match = build_matchups(matchup_rows, waves, proj_by_name, target_course_row, n_rounds=n_rounds)

    print(f"   running full-field finish sim ({finish_trials} trials) ...")
    finish_sim_results = run_finish_sim(proj_by_name, course_row=target_course_row,
                                         n_rounds=4, n_trials=finish_trials)
    W = build_outrights(finish_sim_results, outrights_markets["win"], "win")
    W5 = build_outrights(finish_sim_results, outrights_markets["top5"], "top5")
    W10 = build_outrights(finish_sim_results, outrights_markets["top10"], "top10")
    W20 = build_outrights(finish_sim_results, outrights_markets["top20"], "top20")

    # convert to the compact array shapes the page's JS already expects
    P = [[r["name"], r["proj"], r["ttg"], r["ott"], r["app"], r["put"], r["arg"], r["fit"]] for r in proj]
    M = [[m["a"], m["b"], m["wave"], m["model"], m["market"], m["price"], m["priceB"], m["noVig"],
          m["skillGap"], m["bookCount"]] for m in match]

    data = {
        "meta": {
            "event": event_name,
            "course": course_name,
            "players": len(P),
            "generated": time.strftime("%Y-%m-%d %H:%M:%S"),
            "source": f"DataGolf projections (Path A) + sim_engine.py for model% [{market_used}]",
            "draw_bias": None,   # fill when you add forecast/results logic
        },
        "P": P, "F": F, "M": M, "W": W, "W5": W5, "W10": W10, "W20": W20,
    }
    with open(OUT, "w") as f:
        json.dump(data, f, indent=1)
    print(f"\nWrote {OUT}: event='{event_name}' course='{course_name}' — {len(P)} players, {len(M)} matchups, "
          f"{len(W)}/{len(W5)}/{len(W10)}/{len(W20)} win/top5/top10/top20 rows.")
    return data


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--tour", default="pga", help="pga | euro | opp | alt (try euro if The Open isn't on pga feed)")
    ap.add_argument("--watch", type=int, default=0, help="re-pull every N seconds (0 = once)")
    ap.add_argument("--matchup-rounds", type=int, default=None,
                     help="rounds summed per player in the sim. Default: auto-detected from "
                          "whichever market actually has data (4 for tournament_matchups, "
                          "1 for round_matchups). Set explicitly to override.")
    ap.add_argument("--finish-trials", type=int, default=10000,
                     help="Monte Carlo trials for the full-field win-probability sim. "
                          "10000 runs in a few seconds for a ~156-player field; raise for "
                          "tighter estimates, lower if the pipeline needs to run faster.")
    args = ap.parse_args()
    if args.watch:
        print(f"watch mode: every {args.watch}s (ctrl-C to stop)")
        while True:
            try:
                build(args.tour, matchup_rounds=args.matchup_rounds, finish_trials=args.finish_trials)
            except SystemExit as e:
                print(e)
            time.sleep(args.watch)
    else:
        build(args.tour, matchup_rounds=args.matchup_rounds, finish_trials=args.finish_trials)


if __name__ == "__main__":
    main()
