#!/usr/bin/env python3
"""
Rod's Golf Model — DataGolf ingestion pipeline (Path A: wrap DataGolf)
=====================================================================

Run this on YOUR machine (it needs internet + your DataGolf key).
It pulls the DataGolf feeds, maps them into the shapes Rod's Model expects,
and writes `rods_data.json` next to the HTML page. The page reads that file.

SECURITY: never hard-code your key here or paste it into a chat. Set it as an
env var:   export DG_KEY="your_key_here"

Usage:
    export DG_KEY="..."
    python rods_pipeline.py                 # PGA/euro default -> writes rods_data.json
    python rods_pipeline.py --tour euro      # if The Open is under the euro feed
    python rods_pipeline.py --watch 300      # re-pull every 5 min during the round

Path B migration: everything DataGolf-specific lives in the fetch_* functions and
the MAP_* mapping dicts. To compute your own Birkdale weights later, replace
build_projections()'s use of the decomposition 'fit' field with your own engine's
output — the JSON shape the page consumes does not change.

MODEL vs MARKET (updated this session): matchup "model%" is now generated by
sim_engine.py from projected scores + this event's course-fit variance/blowup —
NOT passed through from DataGolf's own matchup probability. Comparing DataGolf's
model to a DataGolf-derived market number was comparing DG to itself; it couldn't
show real edge no matter what the numbers said. "market%" still comes straight off
DataGolf's book-sourced odds, which is the only side of that comparison that
should come from them.

course_fit_table.json (written by load_course_fit_xlsx.py from
course_fit_template.xlsx) is now read automatically if present, and used both
for the F table and as the course-level scoreSD/blowup input to the sim. Falls
back to the hardcoded Birkdale/Bay Hill rows if that file doesn't exist yet.
"""

import os
import sys
import json
import time
import argparse
import urllib.request
import urllib.parse
import urllib.error

from sim_engine import run_matchup_sim

BASE = "https://feeds.datagolf.com"
OUT  = "rods_data.json"
COURSE_FIT_TABLE = "course_fit_table.json"   # written by load_course_fit_xlsx.py, optional

# ---- endpoints we use for Path A ----
EP = {
    "decomp":   "/preds/player-decompositions",   # SG components + course fit/history
    "pretourn": "/preds/pre-tournament",          # win/top-N + projected scores
    "matchups": "/betting-tools/matchups",        # model vs book 2-ball odds
    "field":    "/field-updates",                  # tee times / wave (AM-PM)
}


def get_key():
    key = os.environ.get("DG_KEY")
    if not key:
        sys.exit("ERROR: set your key first ->  export DG_KEY=\"your_datagolf_key\"")
    return key


def fetch(endpoint, key, **params):
    """GET a DataGolf feed as JSON. Returns parsed python or raises."""
    params.setdefault("file_format", "json")
    params["key"] = key
    url = f"{BASE}{endpoint}?{urllib.parse.urlencode(params)}"
    try:
        with urllib.request.urlopen(url, timeout=30) as r:
            raw = r.read().decode("utf-8")
    except urllib.error.HTTPError as e:
        # surface DataGolf's own error message (bad key, wrong tour, no event, etc.)
        body = e.read().decode("utf-8", "ignore")
        raise SystemExit(f"HTTP {e.code} on {endpoint}: {body[:300]}")
    except urllib.error.URLError as e:
        raise SystemExit(f"Network error on {endpoint}: {e.reason}")
    try:
        return json.loads(raw)
    except json.JSONDecodeError:
        raise SystemExit(f"Non-JSON reply on {endpoint} (first 200 chars): {raw[:200]}")


def as_rows(payload):
    """DataGolf wraps rows in different keys depending on endpoint; normalize to a list."""
    if isinstance(payload, list):
        return payload
    for k in ("players", "matchups", "field", "data", "baseline", "rows"):
        if isinstance(payload, dict) and isinstance(payload.get(k), list):
            return payload[k]
    # some feeds nest under a single dict key -> take first list value found
    if isinstance(payload, dict):
        for v in payload.values():
            if isinstance(v, list):
                return v
    return []


def num(x, nd=1):
    """Round to nd decimals, pass through None for missing (renders as 'nan')."""
    if x is None or x == "":
        return None
    try:
        return round(float(x), nd)
    except (TypeError, ValueError):
        return None


# ------------------------------------------------------------------
# MAP 1: projections table (the `P` array)
# ------------------------------------------------------------------
def build_projections(decomp_payload):
    """
    Map DataGolf player-decompositions -> Rod's `P` rows:
      [name, proj, ttg, ott, app, put, arg, fit]

    DataGolf decomposition fields (names may vary slightly by feed version):
      player_name, sg_total (or 'total'), sg_ott, sg_app, sg_arg, sg_putt, sg_t2g,
      and a course-fit component (often 'course_fit' or 'fit').
    We defensively check a few likely key names for each.
    """
    def pick(row, *names):
        for n in names:
            if n in row and row[n] is not None:
                return row[n]
        return None

    rows = as_rows(decomp_payload)
    out = []
    for r in rows:
        name = pick(r, "player_name", "name")
        if not name:
            continue
        # DataGolf gives skill/SG components; PROJ (projected score) usually comes from
        # pre-tournament preds and is merged in build() below. Store SG parts here.
        out.append({
            "name": normalize_name(name),
            "proj": None,  # filled from pre-tournament merge
            "ttg":  num(pick(r, "sg_t2g", "t2g")),
            "ott":  num(pick(r, "sg_ott", "ott")),
            "app":  num(pick(r, "sg_app", "app")),
            "put":  num(pick(r, "sg_putt", "sg_put", "putt")),
            "arg":  num(pick(r, "sg_arg", "arg")),
            "fit":  num(pick(r, "course_fit", "fit", "fit_adj", "cf")),
            "_dg_id": pick(r, "dg_id"),
        })
    return out


def merge_projected_score(proj_rows, pretourn_payload):
    """Add the projected 72-hole (or per-round) score to each player from pre-tournament preds."""
    def pick(row, *names):
        for n in names:
            if n in row and row[n] is not None:
                return row[n]
        return None
    idx = {}
    for r in as_rows(pretourn_payload):
        nm = normalize_name(pick(r, "player_name", "name") or "")
        # projected score field varies: 'proj_score', 'projected_score', or derive from adj scoring
        idx[nm] = pick(r, "proj_score_avg", "projected_score", "proj_score", "adj_score")
    for row in proj_rows:
        v = idx.get(row["name"])
        row["proj"] = num(v)
    # sort best (lowest) proj first; None sinks to bottom
    proj_rows.sort(key=lambda x: (x["proj"] is None, x["proj"] if x["proj"] is not None else 999))
    return proj_rows


# ------------------------------------------------------------------
# MAP 2: matchups table (the `M` array)
# ------------------------------------------------------------------
def build_matchups(matchup_payload, wave_by_name, proj_by_name, course_row, n_rounds=1):
    """
    Map DataGolf matchup tool -> Rod's `M` rows:
      [playerA, playerB, wave, modelPct, marketPct, price]

    Pulls the two players and the book price/market number from DataGolf, but
    the model% comes from sim_engine.py (projected scores + this event's
    course variance/blowup), NOT from DataGolf's own matchup probability —
    see the module docstring for why that swap matters.
    """
    def pick(row, *names):
        for n in names:
            if n in row and row[n] is not None:
                return row[n]
        return None

    rows = as_rows(matchup_payload)
    pairs = []
    meta = []
    for r in rows:
        p1 = pick(r, "p1_player_name", "player1", "p1")
        p2 = pick(r, "p2_player_name", "player2", "p2")
        if not p1 or not p2:
            continue
        p1 = normalize_name(p1); p2 = normalize_name(p2)
        # book implied — DataGolf exposes odds per book; take a consensus/first available
        market = pick(r, "p1_implied_prob", "market_prob", "p1_book_prob")
        price = pick(r, "p1_odds", "odds", "p1_book_odds", "price")
        market_prob = as_prob(market)
        if market_prob is None and price is not None:
            market_prob = implied_prob_from_american(price)  # derive from the price if DG didn't give a % directly
        w1 = wave_by_name.get(p1, "?"); w2 = wave_by_name.get(p2, "?")
        wave = w1 if w1 == w2 else f"{w1}/{w2}"
        pairs.append((p1, p2))
        meta.append({"a": p1, "b": p2, "wave": wave, "market": market_prob,
                      "price": str(price) if price is not None else "—"})

    # one batched sim call for every matchup on the slate
    model_probs = run_matchup_sim(proj_by_name, pairs, course_row=course_row, n_rounds=n_rounds)

    out = []
    for (p1, p2), m in zip(pairs, meta):
        m["model"] = model_probs.get((p1, p2))  # None if either player had no projection to sim from
        out.append(m)

    # sort by edge desc; unsimmed/unmarketed rows sink to the bottom
    def edge(m):
        if m["model"] is None or m["market"] is None:
            return -999
        return m["model"] - m["market"]
    out.sort(key=edge, reverse=True)
    return out


def as_prob(x):
    """Coerce a probability that might be 0-1 or 0-100 into a 0-1 float."""
    if x is None or x == "":
        return None
    try:
        v = float(x)
    except (TypeError, ValueError):
        return None
    return v / 100.0 if v > 1.0 else v


def implied_prob_from_american(price):
    """American odds -> implied probability (still vig-inclusive; this is 'market', not 'no-vig')."""
    try:
        p = float(price)
    except (TypeError, ValueError):
        return None
    if p > 0:
        return 100.0 / (p + 100.0)
    elif p < 0:
        return -p / (-p + 100.0)
    return None


# ------------------------------------------------------------------
# MAP 3: wave / draw from field updates
# ------------------------------------------------------------------
def build_waves(field_payload):
    """
    Map field-updates -> {player_name: 'AM'|'PM'} using round-1 tee time,
    and compute a draw-bias placeholder (real bias needs forecast + results).
    """
    def pick(row, *names):
        for n in names:
            if n in row and row[n] is not None:
                return row[n]
        return None
    waves = {}
    for r in as_rows(field_payload):
        nm = normalize_name(pick(r, "player_name", "name") or "")
        tt = pick(r, "r1_teetime", "teetime", "tee_time")
        if not nm or not tt:
            continue
        waves[nm] = classify_wave(tt)
    return waves


def classify_wave(teetime):
    """Very rough AM/PM split from a tee-time string like '2026-07-16T13:20' or '1:20 PM'."""
    s = str(teetime).lower()
    if "pm" in s:
        # 12-something pm is borderline; treat >=12:00 as PM
        return "PM"
    if "am" in s:
        return "AM"
    # ISO-ish: grab the hour
    for sep in ("t", " "):
        if sep in s:
            tail = s.split(sep)[-1]
            hh = tail[:2]
            if hh.isdigit():
                return "AM" if int(hh) < 12 else "PM"
    return "?"


# ------------------------------------------------------------------
# name normalization so the three feeds join cleanly
# ------------------------------------------------------------------
def normalize_name(name):
    """DataGolf often returns 'Last, First'; the page shows 'First Last'. Normalize to 'First Last'."""
    name = name.strip()
    if "," in name:
        last, first = [p.strip() for p in name.split(",", 1)]
        return f"{first} {last}"
    return name


# ------------------------------------------------------------------
# course-fit table (the `F` array). Prefers course_fit_table.json, written by
# load_course_fit_xlsx.py from your filled-in course_fit_template.xlsx. Falls
# back to the hardcoded Birkdale/Bay Hill reference rows if that file isn't
# there yet (i.e. you haven't filled in the spreadsheet, or run the loader).
# ------------------------------------------------------------------
def course_fit_placeholder():
    return [
        # [course, renewals, scoreAdj, scoreSD, blowup, wOTT,wAPP,wARG,wPUT, distPrem, recovPen, cutParar, grass]
        ["Royal Birkdale (2026)", 10, 2.4, 3.8, 0.13, 1.10, 1.15, 1.30, 1.00, -0.10, 0.30, 4.0, "fescue/bent"],
        ["Bay Hill (ref: parkland)", 15, 1.8, 3.1, 0.08, 1.15, 1.20, 1.05, 0.85, 0.30, 0.22, 2.0, "bermuda"],
    ]


def load_course_fit(target_course_name_hint="Royal Birkdale"):
    """
    Returns (F, target_row) where F is the page-ready course-fit table and
    target_row is a {'scoreSD':, 'blowup':} dict for whichever row matches
    target_course_name_hint (used to seed the sim's course-level variance) —
    falling back to the first row, or a bare tour-average pair, if no match.
    """
    if os.path.exists(COURSE_FIT_TABLE):
        with open(COURSE_FIT_TABLE) as f:
            data = json.load(f)
        F = data.get("F") or []
        if F:
            target = next((row for row in F if target_course_name_hint.lower() in str(row[0]).lower()), F[0])
            return F, {"scoreSD": target[3], "blowup": target[4]}
    F = course_fit_placeholder()
    target = next((row for row in F if target_course_name_hint.lower() in str(row[0]).lower()), F[0])
    return F, {"scoreSD": target[3], "blowup": target[4]}


def build(tour, matchup_rounds=4):
    key = get_key()
    print(f"[1/4] player decompositions ({tour}) ...")
    decomp = fetch(EP["decomp"], key, tour=tour)
    print(f"[2/4] pre-tournament predictions ({tour}) ...")
    pretourn = fetch(EP["pretourn"], key, tour=tour, odds_format="percent")
    print(f"[3/4] field / tee times ({tour}) ...")
    field = fetch(EP["field"], key, tour=tour)
    print(f"[4/4] matchups ({tour}) ...")
    try:
        matchups = fetch(EP["matchups"], key, tour=tour, market="tournament_matchups", odds_format="american")
    except SystemExit as e:
        print(f"   (matchups unavailable: {e}) — leaving matchups empty")
        matchups = []

    proj = build_projections(decomp)
    proj = merge_projected_score(proj, pretourn)
    waves = build_waves(field)

    F, target_course_row = load_course_fit()
    proj_by_name = {r["name"]: {"mean": r["proj"], "sd": None} for r in proj}
    # NOTE: the "tournament_matchups" market pulled above is a 72-hole market, so the sim
    # sums 4 simulated rounds per player (matchup_rounds=4 below). This ignores cuts/WDs —
    # a real 72-hole matchup settles on made-cut rounds only, which this sim doesn't model
    # yet. Fine for a first pass; flag it if you're pricing outrights near the cut line.
    # If you switch DataGolf's market param to "round_matchups", pass matchup_rounds=1 instead.
    match = build_matchups(matchups, waves, proj_by_name, target_course_row, n_rounds=matchup_rounds)

    # convert to the compact array shapes the page's JS already expects
    P = [[r["name"], r["proj"], r["ttg"], r["ott"], r["app"], r["put"], r["arg"], r["fit"]] for r in proj]
    M = [[m["a"], m["b"], m["wave"], m["model"], m["market"], m["price"]] for m in match]

    data = {
        "meta": {
            "event": "The 154th Open — Royal Birkdale",
            "players": len(P),
            "generated": time.strftime("%Y-%m-%d %H:%M:%S"),
            "source": "DataGolf projections (Path A) + sim_engine.py for model%",
            "draw_bias": None,   # fill when you add forecast/results logic
        },
        "P": P, "F": F, "M": M,
    }
    with open(OUT, "w") as f:
        json.dump(data, f, indent=1)
    print(f"\nWrote {OUT}: {len(P)} players, {len(M)} matchups.")
    return data


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--tour", default="pga", help="pga | euro | opp | alt (try euro if The Open isn't on pga feed)")
    ap.add_argument("--watch", type=int, default=0, help="re-pull every N seconds (0 = once)")
    ap.add_argument("--matchup-rounds", type=int, default=4,
                     help="rounds summed per player in the sim (4 for tournament_matchups, 1 for round_matchups)")
    args = ap.parse_args()
    if args.watch:
        print(f"watch mode: every {args.watch}s (ctrl-C to stop)")
        while True:
            try:
                build(args.tour, matchup_rounds=args.matchup_rounds)
            except SystemExit as e:
                print(e)
            time.sleep(args.watch)
    else:
        build(args.tour, matchup_rounds=args.matchup_rounds)


if __name__ == "__main__":
    main()
